export const [SET_TIMES, SET_DAYS, SET_SELECTED_TIME, SET_SELECTED_DAY] = [
  'SET_TIMES',
  'SET_DAYS',
  'SET_SELECTED_TIME',
  'SET_SELECTED_DAY',
];

export const [MORNING, AFTERNOON, EVENING] = [
  'MORNING',
  'AFTERNOON',
  'EVENING',
];
